alter table SCHEDULEGOODTRY_CREDIT add constraint FK_SCHEDULEGOODTRY_CREDIT_ON_BANK foreign key (BANK_ID) references SCHEDULEGOODTRY_BANK(ID);
create unique index IDX_SCHEDULEGOODTRY_CREDIT_UNIQ_NAME_CREDIT on SCHEDULEGOODTRY_CREDIT (NAME_CREDIT);
create index IDX_SCHEDULEGOODTRY_CREDIT_ON_BANK on SCHEDULEGOODTRY_CREDIT (BANK_ID);
