-- begin SCHEDULEGOODTRY_PAYMENT
alter table SCHEDULEGOODTRY_PAYMENT add constraint FK_SCHEDULEGOODTRY_PAYMENT_ON_CREDIT_OFFER foreign key (CREDIT_OFFER_ID) references SCHEDULEGOODTRY_CREDIT_OFFER(ID)^
create index IDX_SCHEDULEGOODTRY_PAYMENT_ON_CREDIT_OFFER on SCHEDULEGOODTRY_PAYMENT (CREDIT_OFFER_ID)^
-- end SCHEDULEGOODTRY_PAYMENT
-- begin SCHEDULEGOODTRY_CLIENT
alter table SCHEDULEGOODTRY_CLIENT add constraint FK_SCHEDULEGOODTRY_CLIENT_ON_BANK foreign key (BANK_ID) references SCHEDULEGOODTRY_BANK(ID)^
create unique index IDX_SCHEDULEGOODTRY_CLIENT_UNIQ_EMAIL on SCHEDULEGOODTRY_CLIENT (EMAIL)^
create
unique index IDX_SCHEDULEGOODTRY_CLIENT_UNIQ_PASSPORT_NUMBER on SCHEDULEGOODTRY_CLIENT (PASSPORT_NUMBER)^
create
unique index IDX_SCHEDULEGOODTRY_CLIENT_UNIQ_PHONE_NUMBER on SCHEDULEGOODTRY_CLIENT (PHONE_NUMBER)^
create
index IDX_SCHEDULEGOODTRY_CLIENT_ON_BANK on SCHEDULEGOODTRY_CLIENT (BANK_ID)^
-- end SCHEDULEGOODTRY_CLIENT
-- begin SCHEDULEGOODTRY_CREDIT
alter table SCHEDULEGOODTRY_CREDIT
    add constraint FK_SCHEDULEGOODTRY_CREDIT_ON_BANK foreign key (BANK_ID) references SCHEDULEGOODTRY_BANK (ID) ^
create
unique index IDX_SCHEDULEGOODTRY_CREDIT_UNIQ_NAME_CREDIT on SCHEDULEGOODTRY_CREDIT (NAME_CREDIT)^
create
index IDX_SCHEDULEGOODTRY_CREDIT_ON_BANK on SCHEDULEGOODTRY_CREDIT (BANK_ID)^
-- end SCHEDULEGOODTRY_CREDIT
-- begin SCHEDULEGOODTRY_BANK
create
unique index IDX_SCHEDULEGOODTRY_BANK_UNIQ_BANK_NAME on SCHEDULEGOODTRY_BANK (BANK_NAME)^
-- end SCHEDULEGOODTRY_BANK
-- begin SCHEDULEGOODTRY_CREDIT_OFFER
alter table SCHEDULEGOODTRY_CREDIT_OFFER
    add constraint FK_SCHEDULEGOODTRY_CREDIT_OFFER_ON_CLIENT foreign key (CLIENT_ID) references SCHEDULEGOODTRY_CLIENT (ID) ^
alter table SCHEDULEGOODTRY_CREDIT_OFFER
    add constraint FK_SCHEDULEGOODTRY_CREDIT_OFFER_ON_CREDIT foreign key (CREDIT_ID) references SCHEDULEGOODTRY_CREDIT (ID) ^
create
index IDX_SCHEDULEGOODTRY_CREDIT_OFFER_ON_CLIENT on SCHEDULEGOODTRY_CREDIT_OFFER (CLIENT_ID)^
create
index IDX_SCHEDULEGOODTRY_CREDIT_OFFER_ON_CREDIT on SCHEDULEGOODTRY_CREDIT_OFFER (CREDIT_ID)^
-- end SCHEDULEGOODTRY_CREDIT_OFFER
